# config.yml

api_key: "your-openai-api-key"

assistant:
  name: "Cybersecurity Legal Advisor"
  model: "gpt-4o"
  instructions_file_path: "prompts/instructions.md"
  placeholders:
    language: "German"
  tools:
    - "file_search"
    - "code_interpreter"
  max_tokens: 1500
  temperature: 0.7
  top_p: 0.9
  frequency_penalty: 0.0
  presence_penalty: 0.0

thread:
  query_file_path: "prompts/query.md"
  placeholders:
    language: "German"

  attachment_paths:
    - "knowledge/legal/EU-NIS2.pdf"
    - "knowledge/legal/EU-CRA.pdf"

vector_store:
  name: "Cybersecurity Legal Documents"

folders:
  raw: "raw"
  prompts: "prompts"
  outputs: "outputs"

chat_completion:
  model: "gpt-4o-mini"
  max_tokens: 1500
  temperature: 0.7
  top_p: 0.9
  frequency_penalty: 0.0
  presence_penalty: 0.0
  prompt_file_path: "prompts/convert_to_markdown.md"
  placeholders:
    language: "German"


